server:
  port: 8080

management:
  endpoints:
    web:
      expose: "*"
      base-path: "/"
      path-mapping:
        prometheus: "metrics"
      exposure:
        include: [ "health", "info", "prometheus" ]
  info:
    git:
      mode: full
spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;CASE_INSENSITIVE_IDENTIFIERS=true
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: true
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: false
        format_sql: false
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    show-sql: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

logging:
  level:
    root: info
    org.springframework.jdbc.datasource: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p --- [%15.15t] %-40.40logger{39} :: %X{X-Trace-Id} : %m%n%ex{full}"